name: TGconsole
main: ru.stormcraft.tgconsole.Main
version: 0.8
author: Azim
depend: [TelegramBotsAPI]
commands:
  tgconsole:
    description: TGConsole commands info
    aliases: tgc
    permission: tgconsole.info