name: TGconsole
main: ru.stormcraft.tgconsole.Main
version: 1.10.1
load: STARTUP
author: Azim
depend: 
commands:
  tgconsole:
    description: TGConsole commands info
    aliases: tgc
    permission: tgconsole.info